# Generated by Django 4.2.5 on 2023-11-26 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('author', models.CharField(blank=True, default='Nenhum', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavouritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('iso2', models.CharField(blank=None, default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('comments', models.ManyToManyField(blank=True, default=None, to='TripHelperApp.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=10)),
                ('comments', models.ManyToManyField(blank=True, default=None, to='TripHelperApp.comment')),
                ('favPlaces', models.ManyToManyField(blank=True, default=None, to='TripHelperApp.favouriteplace')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
