# Generated by Django 4.2.5 on 2023-10-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelperApp', '0002_user_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SimpleUser',
        ),
    ]
