# Generated by Django 4.2.5 on 2023-10-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelperApp', '0005_favoriteplace_post_perfil_favplaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteplace',
            name='img_url',
        ),
        migrations.AddField(
            model_name='favoriteplace',
            name='iso2',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
