# Generated by Django 4.2.5 on 2023-10-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelperApp', '0007_alter_favoriteplace_iso2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteplace',
            name='iso2',
            field=models.CharField(blank=None, default=None, max_length=2),
        ),
    ]
