# Generated by Django 4.2.5 on 2023-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelperApp', '0011_alter_perfil_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
