# Generated by Django 4.2.5 on 2023-11-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelperApp', '0013_alter_comment_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritePlace',
            new_name='FavouritePlace',
        ),
    ]
